name: stdock
channels:
  - defaults
  - conda-forge
dependencies:
  - pip
  - python>=3.10
  - ipympl
  - ipython
  - openbabel
  - pip:
     - -e .  # install git checkout of stdock in editable mode
