{% set name = "stdock" %}
{% set version = "0.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/rglez/stdock/archive/v{{ version }}.tar.gz
  sha256: 58d9b4cf4bc86c91f3b7430539638bf114d078cf35bb810f0797c2be9f5ec861

build:
  entry_points:
    - stdock = stdock.stdock:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python
    - setuptools >=46.1.0
    - setuptools-scm >=5
    - pip
  run:
    - python
    - setuptools >=68.2.2,<68.3.dev0
    - matplotlib-base >=3.8.2,<3.9.dev0
    - pandas >=2.1.4,<2.2.dev0
    - scipy >=1.11.4,<1.12.dev0
    - numpy >=1.23.5,<1.24.dev0
    - rdkit >=2023.9.3,<2023.10.dev0
    - prody >=2.4.1,<2.5.dev0
    - bitarray >=2.9.1,<2.10.dev0
    - tqdm >=4.66.1,<4.67.dev0
    - mdtraj >=1.9.9,<1.10.dev0
    - tabulate >=0.9.0,<0.10.dev0
    - numba >=0.58.1,<0.59.dev0
    - numpy-indexed
    - openbabel >=3.1.1,<3.2.dev0

test:
  imports:
    - stdock
  commands:
    - pip check
    - stdock --help
  requires:
    - pip

about:
  home: https://github.com/pyscaffold/pyscaffold/
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - rglez
